// Generated by Selenium IDE
package test;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestRoomServiceTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty( "webdriver.chrome.driver", "C:\\Users\\Fernando\\Deskop\\chromedriver\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testRoomService() {
    driver.get("http://localhost:8080/ISST-20-Conc/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.name("dni")).click();
    driver.findElement(By.name("dni")).sendKeys("aa");
    driver.findElement(By.name("room")).sendKeys("aa");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector(".room img")).click();
    driver.findElement(By.name("forRoom")).click();
    driver.findElement(By.name("forRoom")).sendKeys("508");
    driver.findElement(By.name("type")).click();
    {
      WebElement dropdown = driver.findElement(By.name("type"));
      dropdown.findElement(By.xpath("//option[. = 'Servicio de tintoreria']")).click();
    }
    driver.findElement(By.name("type")).click();
    driver.findElement(By.name("description")).click();
    driver.findElement(By.name("description")).sendKeys("Quiero un tinte rojo");
    driver.findElement(By.name("date")).click();
    driver.findElement(By.name("date")).sendKeys("0002-12-02");
    driver.findElement(By.name("date")).sendKeys("0020-12-02");
    driver.findElement(By.name("date")).sendKeys("0202-12-02");
    driver.findElement(By.name("date")).sendKeys("2020-12-02");
    driver.findElement(By.name("addComents")).click();
    driver.findElement(By.name("addComents")).sendKeys("Nada mas");
    driver.findElement(By.cssSelector(".botonRegistro")).click();
    driver.findElement(By.cssSelector(".atras img")).click();
    driver.findElement(By.cssSelector(".room img")).click();
    driver.findElement(By.cssSelector("form:nth-child(2) > .cancRoom")).click();
    driver.findElement(By.name("myType")).click();
    {
      WebElement dropdown = driver.findElement(By.name("myType"));
      dropdown.findElement(By.xpath("//option[. = 'Servicio de tintoreria']")).click();
    }
    driver.findElement(By.name("myType")).click();
    driver.findElement(By.name("description")).click();
    driver.findElement(By.name("description")).sendKeys("Quiero un tinte verde");
    driver.findElement(By.cssSelector(".botonEditar")).click();
    driver.findElement(By.cssSelector(".navbar-brand > img")).click();
    driver.findElement(By.cssSelector(".room img")).click();
    driver.findElement(By.cssSelector("form:nth-child(1) > .cancRoom")).click();
    driver.findElement(By.cssSelector(".atras img")).click();
    driver.findElement(By.cssSelector(".room img")).click();
    driver.findElement(By.name("forRoom")).click();
    driver.findElement(By.name("forRoom")).sendKeys("508");
    driver.findElement(By.name("type")).click();
    {
      WebElement dropdown = driver.findElement(By.name("type"));
      dropdown.findElement(By.xpath("//option[. = 'Compra de jamon']")).click();
    }
    driver.findElement(By.name("type")).click();
    driver.findElement(By.name("description")).click();
    driver.findElement(By.cssSelector(".atras img")).click();
    driver.findElement(By.cssSelector(".button")).click();
  }
}
